### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by sagikazarmark** [K-Phoen/SitemapGenerator#4]
Apart from the changes I suggested in the previous issue, I have a few ideas to improve package quality:
- [ ] Coding Standard/Style:
  - [ ] Add CS checking
  - [ ] Docblocks
    - [ ] Remove "noise" (like: string $url The URL <- Makes no sense IMO)
    - [ ] Add dockblocks when missing
    - [x] Fix dockblocks where something is wrong (like Entitymanager instead of RouteInterface
  - [ ] Add editorconfig
- [ ] Code
  - [x] _Array typehints (`setImages`, `setVideos`)_
  - [x] _Drop `Interface` suffix: Symfony, Zend and the FIG still pushes it, but fortunately more and more developers realize, it's evil (reference: http://verraes.net/2013/09/sensible-interfaces/)_
  - [ ] _Separate `AbstractProvider` into smaller components: extract route generation logic_
  - [ ] _Remove `BaseFormatter`_
- [ ] Package
  - [ ] Add a Changelog
  - [x] Add a CONTRIBUTING guide
  - [ ] Remove unnecessary defaults from PHPUnit config
  - [ ] Add the Contributor Code of Conduct
  - [x] Change to PSR-4 autoloading (and remove unnecessary custom ones)
  - [ ] _Separate components requiring external dependencies into separate packages (doctrine, propel)_
  - [ ] Unit test against lowest dependencies
- [ ] New Features
  - [ ] Add support for custom types: http://www.sitemaps.org/protocol.html#extending
  - [ ] Add support for setting sitemap options directly in route options (RouteCollectionProvider)
  - [ ] Add a caching layer for providers with expensive calculations
  - [x] Add a `ChangeFrequency` class/interface with common change constants
  - [ ] Introduce streaming somehow to improve memory efficiency

These are the things I have in my mind so far. 

I marked BC breaking changes with _italic_. In these cases TODOs and deprecation warnings should be triggered.

Ultimately I think this project could also have it's own organization. Like sitemaphp (which I immediately registered, just in case :D, can invite you if interested)

There are many others as well, but I found yours to have the most decent API and workflow (actually I started to develop exactly the same)

**Comment by K-Phoen** [comment]
I referenced the improvements you listed here in [a new issue](https://github.com/K-Phoen/SitemapGenerator/issues/9) that will contain the things I want to see in a new version. I also have created separated issues for some of the items listed here.

Feel free to contribute if you're interested :)

**Comment by sagikazarmark** [comment]
Will do, thanks for reply and consideration.
